#!/bin/bash

if [ -z "$FETUS_PP" ]; then
	FETUS_PP=./fetus_pp
fi
if [ -z "$FETUS_C" ]; then
	FETUS_C=./fetus_c
fi
if [ -z "$FETUS_VM" ]; then
	FETUS_VM=./fetus_vm
fi

$FETUS_PP $1 - | $FETUS_C - - | $FETUS_VM - $2 $3 $4 $5 $6 $7 $8 $9
