#!/bin/bash

if [ -z "$FETUS_PP" ]; then
	FETUS_PP=./fetus_pp
fi
if [ ! -f "$FETUS_PP" ]; then
	echo "Can't find Fetus preprocessor ($FETUS_PP)"
	exit 1
fi
if [ -z "$FETUS_C" ]; then
	FETUS_C=./fetus_c
fi
if [ ! -f "$FETUS_C" ]; then
	echo "Can't find Fetus compiler ($FETUS_C)"
	exit 1
fi
if [ -z "$FETUS_VM" ]; then
	FETUS_VM=./fetus_vm
fi
if [ ! -f "$FETUS_VM" ]; then
	echo "Can't find Fetus VM ($FETUS_VM)"
	exit 1
fi

$FETUS_PP $1 - | $FETUS_C - - | $FETUS_VM - $2 $3 $4 $5 $6 $7 $8 $9
