#!/bin/bash

if [ -z "$FETUS_PP" ]; then
	FETUS_PP=./fetus_pp
fi
if [ ! -f "$FETUS_PP" ]; then
	echo "Can't find Fetus preprocessor ($FETUS_PP)"
	exit 1
fi
if [ -z "$FETUS_C" ]; then
	FETUS_C=./fetus_c
fi
if [ ! -f "$FETUS_C" ]; then
	echo "Can't find Fetus compiler ($FETUS_C)"
	exit 1
fi
if [ -z "$FETUS_VM" ]; then
	FETUS_VM=./fetus_vm
fi
if [ ! -f "$FETUS_VM" ]; then
	echo "Can't find Fetus VM ($FETUS_VM)"
	exit 1
fi

while getopts ":ECo:" opt; do
	case $opt in
		E)
			PREPROCESS_ONLY=1
			;;
		C)
			COMPILE_ONLY=1
			;;
		o)
			OUTPUT_NAME=$OPTARG
			;;
	esac
	shift $((OPTIND-1))
	OPTIND=$((OPTIND-1))
done

if [ $PREPROCESS_ONLY ]; then
	$FETUS_PP $1 $OUTPUT_NAME
	exit 0
fi

if [ $COMPILE_ONLY ]; then
	$FETUS_PP $1 | $FETUS_C - $OUTPUT_NAME
	exit 0
fi

$FETUS_PP $1
if [ $? -ne 0 ]; then
	exit $?
fi

if [ $PREPROCESS_ONLY ]; then
	exit 0
fi

$FETUS_C a.ftsp

if [ $? -ne 0 ]; then
	exit $?
fi

if [ $COMPILE_ONLY ]; then
	exit 0
fi

$FETUS_VM a.ftsb $2 $3 $4 $5 $6 $7 $8 $9
