#!/bin/bash

if [ -z "$SOMETHING_C" ]; then
	SOMETHING_C=./something_c
fi
if [ ! -f "$SOMETHING_C" ]; then
	echo "Can't find Something compiler ($SOMETHING_C)"
	exit 1
fi
if [ -z "$FETUS_VM" ]; then
	FETUS_VM=./fetus_vm
fi
if [ ! -f "$FETUS_VM" ]; then
	echo "Can't find Fetus VM ($FETUS_VM)"
	exit 1
fi

while getopts ":Co:" opt; do
	case $opt in
		C)
			COMPILE_ONLY=1
			;;
		o)
			OUTPUT_NAME=$OPTARG
			;;
	esac
	shift $((OPTIND-1))
	OPTIND=$((OPTIND-1))
done

if [ $COMPILE_ONLY ]; then
	$SOMETHING_C $1 $OUTPUT_NAME
	exit 0
fi

$SOMETHING_C $1
if [ $? -ne 0 ]; then
	exit $?
fi
$FETUS_VM a.ftsb $2 $3 $4 $5 $6 $7 $8 $9
