#!/usr/bin/env lua

input = io.open(arg[1], "r")
output = io.open(arg[2], "w")

text = [[
#include <iostream>
#include <fstream>
#include <sstream>
#include <cstring>
#include "vm.h"

using namespace std;
using namespace Fetus;

char program[] = {
%s
};

int main(int argc, const char **argv)
{
	VM vm;
	Parser p(&vm);

	p.parseBlob(program, sizeof(program)/sizeof(char));
	
	vm.run();
	return 0;
}
]]

program = ""

char = input:read(1)
while char do
	program = ("%s, 0x%x"):format(program, char:byte())
	char = input:read(1)
end
output:write(text:format(program:sub(3, -1)))
